### ISSUE TITLE
Time tracking with form

### ISSUE THREAD

**Issue by mynkgupta22** [masum-raja/HelloBonsai#41]
- [x] time tracking form
- [x] added data from the form
- [x] append the data and show in table form
- [ ]
